# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-03cb3418-dd05-48c8-ab5d-256951f428bc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-03cb3418-dd05-48c8-ab5d-256951f428bc".device = "/dev/disk/by-uuid/03cb3418-dd05-48c8-ab5d-256951f428bc";

  boot.initrd.luks.devices."luks-ab15abdc-aefd-45e5-8ead-dbaf03c693cc".device = "/dev/disk/by-uuid/ab15abdc-aefd-45e5-8ead-dbaf03c693cc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FDAE-C0AC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ab15abdc-aefd-45e5-8ead-dbaf03c693cc"; }
    ];

  fileSystems."/mnt/win" =
    { device = "/dev/disk/by-uuid/322666BE266682A9";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" "gid=100" "umask=0022" "fmask=0022" "dmask=0022" "nofail" ];
    };

  fileSystems."/mnt/500gb" =
    { device = "/dev/disk/by-uuid/63A390932FC7B574";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" "gid=100" "umask=0022" "fmask=0022" "dmask=0022" "nofail" ];
    };

  # Ensure mount point ownership is set correctly
  systemd.tmpfiles.rules = [
    "d /mnt/win 0755 stefanmatic users -"
    "d /mnt/500gb 0755 stefanmatic users -"
  ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  hardware.graphics.extraPackages = with pkgs; [ rocmPackages.clr.icd ];
}
