# Hardware configuration for Raspberry Pi Zero 2W Magic Mirror
# This is optimized for Pi Zero 2W with display output requirements
# Replace this with actual hardware-configuration.nix generated by nixos-generate-config

{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ ];

  # Pi Zero 2W specific kernel modules
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "usbhid"
    "usb_storage"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Root filesystem optimized for Magic Mirror Zero 2W
  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS_SD";
    fsType = "ext4";
    options = [
      "noatime" # Reduce SD card writes
      "commit=60" # Less frequent commits for SD card longevity
    ];
  };

  # Optional: Separate boot partition (uncomment if using)
  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-label/FIRMWARE";
  #   fsType = "vfat";
  #   options = [ "noatime" ];
  # };

  # No swap devices - using zRAM instead (configured in rpi-zero2w.nix)
  swapDevices = [ ];

  # Network configuration for Magic Mirror
  networking = {
    useDHCP = lib.mkDefault true;
    # Zero 2W WiFi interface
    interfaces.wlan0.useDHCP = lib.mkDefault true;
  };

  # Platform specification
  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";

  # Pi Zero 2W specific hardware optimizations for Magic Mirror

  # Device tree configuration for display output
  hardware.deviceTree = {
    enable = true;
    # Use Pi 3 kernel for Zero 2W compatibility
    kernelPackage = pkgs.linuxKernel.packages.linux_rpi3.kernel;
    filter = "*2837*"; # BCM2837 for Zero 2W

    # Custom overlays for Magic Mirror display optimization
    overlays = [
      # Enable I2C for potential sensors/controls
      {
        name = "enable-i2c";
        dtsText = ''
          /dts-v1/;
          /plugin/;

          / {
            compatible = "brcm,bcm2835";

            fragment@0 {
              target = <&i2c1>;
              __overlay__ {
                status = "okay";
                pinctrl-names = "default";
                pinctrl-0 = <&i2c1_pins>;
                clock-frequency = <100000>;
              };
            };
          };
        '';
      }

      # Optional: PWM overlay for backlight control
      {
        name = "pwm-backlight";
        dtsText = ''
          /dts-v1/;
          /plugin/;

          / {
            compatible = "brcm,bcm2835";

            fragment@0 {
              target-path = "/";
              __overlay__ {
                backlight {
                  compatible = "pwm-backlight";
                  pwms = <&pwm 0 50000>;
                  brightness-levels = <0 6 8 12 16 24 32 48 64 96 128 160 192 224 255>;
                  default-brightness-level = <6>;
                  status = "okay";
                };
              };
            };
          };
        '';
      }
    ];
  };

  # Memory configuration optimized for Magic Mirror on Zero 2W
  boot.kernel.sysctl = {
    # Optimize memory management for limited RAM
    "vm.dirty_ratio" = 15; # Reduce dirty memory threshold
    "vm.dirty_background_ratio" = 5; # Background writeback threshold
    "vm.swappiness" = 60; # Balanced swapping for zRAM
    "vm.vfs_cache_pressure" = 50; # Keep more directory/inode cache

    # Network optimizations for Magic Mirror
    "net.core.rmem_default" = 65536;
    "net.core.rmem_max" = 134217728;
    "net.core.wmem_default" = 65536;
    "net.core.wmem_max" = 134217728;
  };

  # Hardware features specific to Magic Mirror Zero 2W
  hardware = {
    # Enable basic hardware support
    enableRedistributableFirmware = lib.mkForce false;
    firmware = [ pkgs.raspberrypiWirelessFirmware ];

    # Enable I2C for potential Magic Mirror sensors/controls
    i2c.enable = true;

    # SPI disabled by default (enable if needed for displays)
    spi.enable = false;

    # Audio disabled to save resources (Magic Mirror typically doesn't need audio)
    pulseaudio.enable = false;
    sound.enable = false;
  };

  # Boot optimization for faster Magic Mirror startup
  boot.kernelParams = [
    # Display/graphics optimization
    "console=tty1" # Use tty1 for console
    "fbcon=map:0" # Map framebuffer console

    # Performance optimization
    "cgroup_enable=memory" # Enable memory cgroups
    "cgroup_memory=1" # Memory cgroup support

    # Reduce boot noise for clean display
    "quiet"
    "splash"
    "plymouth.ignore-serial-consoles"

    # SD card optimization
    "rootwait"
    "elevator=mq-deadline" # Better scheduler for SD cards
  ];

  # Services optimization for Magic Mirror
  systemd = {
    # Faster boot for Magic Mirror display
    services = {
      # Disable unnecessary services for Magic Mirror
      "systemd-random-seed".enable = false;
      "systemd-firstboot".enable = false;
    };

    # Optimize systemd for faster Magic Mirror startup
    extraConfig = ''
      DefaultTimeoutStartSec=30s
      DefaultTimeoutStopSec=10s
    '';
  };
}
