{ config, pkgs, lib, ... }:

{
  # Niri configuration file for DMS integration
  # DMS itself is installed at system-level in hosts/zvijer/configuration.nix

  # Create DMS config directory structure
  home.file.".config/niri/dms/colors.kdl".text = ''
    // DMS color configuration
    // Colors are dynamically generated by matugen based on wallpaper
  '';

  home.file.".config/niri/dms/layout.kdl".text = ''
    // DMS layout configuration
    layout {
        gaps 5
        background-color "transparent"
    }
  '';

  home.file.".config/niri/dms/alttab.kdl".text = ''
    // DMS alt-tab configuration
  '';

  home.file.".config/niri/dms/binds.kdl".text = ''
    // DMS keybindings
  '';

  home.file.".config/niri/config.kdl".text = ''
    // Niri configuration for DankMaterialShell
    // This config follows DMS official documentation:
    // https://danklinux.com/docs/dankmaterialshell/compositors

    // Include DMS config files (colors, layout, alttab, binds)
    include "dms/colors.kdl"
    include "dms/layout.kdl"
    include "dms/alttab.kdl"
    include "dms/binds.kdl"

    // Spawn DMS at startup
    spawn-at-startup "dms" "run"

    // Clipboard history (optional)
    spawn-at-startup "bash" "-c" "wl-paste --watch cliphist store &"

    // Environment variables
    environment {
      XDG_CURRENT_DESKTOP "niri"
      QT_QPA_PLATFORM "wayland"
      ELECTRON_OZONE_PLATFORM_HINT "auto"
      QT_QPA_PLATFORMTHEME "gtk3"
      QT_QPA_PLATFORMTHEME_QT6 "gtk3"
    }

    // Layout configuration
    layout {
      center-focused-column "never"
      default-column-width { proportion 0.5; }
      preset-column-widths {
        proportion 0.33
        proportion 0.5
        proportion 0.66
      }
    }

    // Layer rules for DMS integration
    layer-rule {
      match namespace="^quickshell$"
      place-within-backdrop true
    }

    layer-rule {
      match namespace="dms:blurwallpaper"
      place-within-backdrop true
    }

    // Window rules for DMS
    window-rule {
      match app-id=r#"org.quickshell$"#
      open-floating true
    }

    // GNOME apps styling
    window-rule {
      match app-id=r#"^org\.gnome\."#
      draw-border-with-background false
      geometry-corner-radius 12
      clip-to-geometry true
    }

    // Terminal apps - no border background
    window-rule {
      match app-id=r#"^org\.wezfurlong\.wezterm$"#
      match app-id="Alacritty"
      match app-id="zen"
      match app-id="com.mitchellh.ghostty"
      match app-id="kitty"
      draw-border-with-background false
    }

    // Inactive windows opacity
    window-rule {
      match is-active=false
      opacity 0.9
    }

    // Default rounded corners
    window-rule {
      geometry-corner-radius 12
      clip-to-geometry true
    }

    // DMS keybindings
    binds {
      // Application Launchers
      Mod+Space hotkey-overlay-title="Application Launcher" {
        spawn "dms" "ipc" "call" "spotlight" "toggle";
      }
      Mod+V hotkey-overlay-title="Clipboard Manager" {
        spawn "dms" "ipc" "call" "clipboard" "toggle";
      }
      Mod+M hotkey-overlay-title="Task Manager" {
        spawn "dms" "ipc" "call" "processlist" "focusOrToggle";
      }
      Mod+Comma hotkey-overlay-title="Settings" {
        spawn "dms" "ipc" "call" "settings" "focusOrToggle";
      }
      Mod+N hotkey-overlay-title="Notification Center" {
        spawn "dms" "ipc" "call" "notifications" "toggle";
      }
      Mod+Y hotkey-overlay-title="Browse Wallpapers" {
        spawn "dms" "ipc" "call" "dankdash" "wallpaper";
      }

      // Security
      Mod+Alt+L hotkey-overlay-title="Lock Screen" {
        spawn "dms" "ipc" "call" "lock" "lock";
      }

      // Audio Controls
      XF86AudioRaiseVolume allow-when-locked=true {
        spawn "dms" "ipc" "call" "audio" "increment" "3";
      }
      XF86AudioLowerVolume allow-when-locked=true {
        spawn "dms" "ipc" "call" "audio" "decrement" "3";
      }
      XF86AudioMute allow-when-locked=true {
        spawn "dms" "ipc" "call" "audio" "mute";
      }

      // Brightness Controls
      XF86MonBrightnessUp allow-when-locked=true {
        spawn "dms" "ipc" "call" "brightness" "increment" "5" "";
      }
      XF86MonBrightnessDown allow-when-locked=true {
        spawn "dms" "ipc" "call" "brightness" "decrement" "5" "";
      }

      // Window management
      Mod+Q { close-window; }
      Mod+Return { spawn "ghostty"; }

      // Window focus (Vim-style)
      Mod+H { focus-column-left; }
      Mod+L { focus-column-right; }
      Mod+J { focus-window-down; }
      Mod+K { focus-window-up; }

      // Window movement
      Mod+Shift+H { move-column-left; }
      Mod+Shift+L { move-column-right; }
      Mod+Shift+J { move-window-down; }
      Mod+Shift+K { move-window-up; }

      // Workspaces
      Mod+1 { focus-workspace 1; }
      Mod+2 { focus-workspace 2; }
      Mod+3 { focus-workspace 3; }
      Mod+4 { focus-workspace 4; }
      Mod+5 { focus-workspace 5; }

      Mod+Shift+1 { move-column-to-workspace 1; }
      Mod+Shift+2 { move-column-to-workspace 2; }
      Mod+Shift+3 { move-column-to-workspace 3; }
      Mod+Shift+4 { move-column-to-workspace 4; }
      Mod+Shift+5 { move-column-to-workspace 5; }

      // Screenshot
      Print { spawn "sh" "-c" "grimblast copy area"; }
    }

    // Prefer dark theme
    prefer-no-csd true
  '';
}
