{ config, pkgs, lib, ... }:

{
  # StreamController (Stream Deck Plus) configuration management
  # Manages pages and settings for ZVIJER-specific Stream Deck setup

  # Note: StreamController uses Flatpak, so data is stored in:
  # ~/.var/app/com.core447.StreamController/data/

  # Skip onboarding screen
  home.file.".var/app/com.core447.StreamController/data/.skip-onboarding".text = "";

  # Use activation script to COPY (not symlink) configuration files
  # This allows StreamController to modify them without permission errors
  home.activation.streamcontroller = lib.hm.dag.entryAfter ["writeBoundary"] ''
    STREAMCONTROLLER_DATA="$HOME/.var/app/com.core447.StreamController/data"

    # Create directories if they don't exist
    mkdir -p "$STREAMCONTROLLER_DATA/pages"
    mkdir -p "$STREAMCONTROLLER_DATA/settings"

    # Copy page files (writable)
    $DRY_RUN_CMD cp -f ${./pages/Main.json} "$STREAMCONTROLLER_DATA/pages/Main.json"
    $DRY_RUN_CMD cp -f ${./pages/Emoji.json} "$STREAMCONTROLLER_DATA/pages/Emoji.json"

    # Copy settings files (writable)
    $DRY_RUN_CMD cp -f ${./settings/settings.json} "$STREAMCONTROLLER_DATA/settings/settings.json"
    $DRY_RUN_CMD cp -f ${./settings/migrations.json} "$STREAMCONTROLLER_DATA/settings/migrations.json"

    # Make files writable
    $DRY_RUN_CMD chmod 644 "$STREAMCONTROLLER_DATA/pages"/*.json
    $DRY_RUN_CMD chmod 644 "$STREAMCONTROLLER_DATA/settings"/*.json

    echo "StreamController configuration files copied (writable)"
  '';

  # Note: Configuration files are COPIED (not symlinked) so StreamController can modify them
  # To save your changes back to dotfiles, manually copy the files:
  #   cp ~/.var/app/com.core447.StreamController/data/pages/*.json ~/.dotfiles/user/app/streamcontroller/pages/
  #   cp ~/.var/app/com.core447.StreamController/data/settings/*.json ~/.dotfiles/user/app/streamcontroller/settings/
  #
  # Plugins, icons, wallpapers, and cached data are excluded
  # as they can be regenerated by StreamController
}
