{ inputs, pkgs, pkgs-unstable, ... }: {
  home.sessionVariables.NIXOS_OZONE_WL = "1";

  imports = [
    ./hyprlock.nix
    ./hyprswitch.nix
  ];

  home.packages = (with pkgs; [
    inputs.hyprlock.packages.${pkgs.system}.default
  ]);

  wayland.windowManager.hyprland = {
    enable = true;
    package = inputs.hyprland.packages.${pkgs.system}.hyprland;
    #plugins = [
    #  inputs.hyprland-plugins.packages.${pkgs.system}.hyprtrails
    #  inputs.hyprland-plugins.packages.${pkgs.system}.hyprexpo
    #  inputs.hyprgrass.packages.${pkgs.system}.default
    #];
    settings = { };
    extraConfig = ''
      # #######################################################################################
      # AUTOGENERATED HYPR CONFIG.
      # PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
      # OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
      # #######################################################################################

      #autogenerated = 1 # remove this line to remove the warning

      # This is an example Hyprland config file.
      # Refer to the wiki for more information.
      # https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

      # Please note not all available settings / options are set here.
      # For a full list, see the wiki

      # You can split this configuration into multiple files
      # Create your files separately and then link them to this file like this:
      # source = ~/.config/hypr/myColors.conf


      ################
      ### MONITORS ###
      ################

      # See https://wiki.hyprland.org/Configuring/Monitors/
      #monitor=,preferred,auto,auto
      monitor=DP-1, 3440x1440@144, 1080x45, 1
      monitor=DP-2, 1920x1080,4520x300, 1
      monitor=DP-3, 1920x1080, 0x0, 1, transform, 3


      ###################
      ### MY PROGRAMS ###
      ###################

      # See https://wiki.hyprland.org/Configuring/Keywords/

      # Set programs that you use
      $terminal = kitty
      $fileManager = dolphin
      $menu = rofi -show drun -show-icons
      #$menu = wofi --show drun


      #################
      ### AUTOSTART ###
      #################

      # Autostart necessary processes (like notifications daemons, status bars, etc.)
      # Or execute your favorite apps at launch like this:

      #exec-once = $terminal
      exec-once = hyprpaper &
      exec-once = nm-applet &
      #exec-once = code
      #exec-once = chromium
      exec-once = waybar &
      exec-once = hyprswitch init --custom-css /home/fallen/.config/hypr/hyprswitch.css &
      exec-once = flameshot &
      exec-once = nm-applet &
      exec-once = kwalletd6 &


      #############################
      ### ENVIRONMENT VARIABLES ###
      #############################

      # See https://wiki.hyprland.org/Configuring/Environment-variables/

      env = XCURSOR_SIZE,24
      env = HYPRCURSOR_SIZE,24


      #####################
      ### LOOK AND FEEL ###
      #####################

      # Refer to https://wiki.hyprland.org/Configuring/Variables/

      # https://wiki.hyprland.org/Configuring/Variables/#general
      general { 
          gaps_in = 5
          gaps_out = 20

          border_size = 3

          # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
          col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
          col.inactive_border = rgba(595959aa)

          # Set to true enable resizing windows by clicking and dragging on borders and gaps
          resize_on_border = true 

          # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
          allow_tearing = false

          layout = dwindle
      }

      # https://wiki.hyprland.org/Configuring/Variables/#decoration
      decoration {
          rounding = 10

          # Change transparency of focused and unfocused windows
          active_opacity = 1.0
          inactive_opacity = 1.0

          drop_shadow = true
          shadow_range = 4
          shadow_render_power = 3
          col.shadow = rgba(1a1a1aee)

          # https://wiki.hyprland.org/Configuring/Variables/#blur
          blur {
              enabled = true
              size = 3
              passes = 1

              vibrancy = 0.1696
          }
      }

      # https://wiki.hyprland.org/Configuring/Variables/#animations
      animations {
          enabled = true

          # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

          bezier = myBezier, 0.05, 0.9, 0.1, 1.05

          animation = windows, 1, 7, myBezier
          animation = windowsOut, 1, 7, default, popin 80%
          animation = border, 1, 10, default
          animation = borderangle, 1, 8, default
          animation = fade, 1, 7, default
          animation = workspaces, 1, 6, default
      }

      # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
      dwindle {
          pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
          preserve_split = true # You probably want this
      }

      # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
      master {
          new_status = master
      }

      # https://wiki.hyprland.org/Configuring/Variables/#misc
      misc { 
          force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
          disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
      }


      #############
      ### INPUT ###
      #############

      # https://wiki.hyprland.org/Configuring/Variables/#input
      input {
          kb_layout = us
          kb_variant =
          kb_model =
          kb_options =
          kb_rules =

          follow_mouse = 1

          sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

          touchpad {
              natural_scroll = true
              scroll_factor = 0.7
          }
      }

      # https://wiki.hyprland.org/Configuring/Variables/#gestures
      gestures {
          workspace_swipe = false
      }

      # Example per-device config
      # See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
      device {
          name = epic-mouse-v1
          sensitivity = -0.5
      }


      ###################
      ### KEYBINDINGS ###
      ###################

      # See https://wiki.hyprland.org/Configuring/Keywords/
      $mainMod = SUPER # Sets "Windows" key as main modifier

      # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
      bind = $mainMod, Q, exec, $terminal
      bind = $mainMod, C, killactive,
      bind = $mainMod, M, exit,
      bind = $mainMod, E, exec, $fileManager
      bind = $mainMod, V, togglefloating,
      bind = $mainMod, R, exec, $menu
      bind = $mainMod, P, pseudo, # dwindle
      bind = $mainMod, J, togglesplit, # dwindle

      # Move focus with mainMod + arrow keys
      bind = $mainMod, left, movefocus, l
      bind = $mainMod, right, movefocus, r
      bind = $mainMod, up, movefocus, u
      bind = $mainMod, down, movefocus, d

      # Switch workspaces with mainMod + [0-9]
      bind = $mainMod, 1, workspace, 1
      bind = $mainMod, 2, workspace, 2
      bind = $mainMod, 3, workspace, 3
      bind = $mainMod, 4, workspace, 4
      bind = $mainMod, 5, workspace, 5
      bind = $mainMod, 6, workspace, 6
      bind = $mainMod, 7, workspace, 7
      bind = $mainMod, 8, workspace, 8
      bind = $mainMod, 9, workspace, 9
      bind = $mainMod, 0, workspace, 10

      # Move active window to a workspace with mainMod + SHIFT + [0-9]
      bind = $mainMod SHIFT, 1, movetoworkspace, 1
      bind = $mainMod SHIFT, 2, movetoworkspace, 2
      bind = $mainMod SHIFT, 3, movetoworkspace, 3
      bind = $mainMod SHIFT, 4, movetoworkspace, 4
      bind = $mainMod SHIFT, 5, movetoworkspace, 5
      bind = $mainMod SHIFT, 6, movetoworkspace, 6
      bind = $mainMod SHIFT, 7, movetoworkspace, 7
      bind = $mainMod SHIFT, 8, movetoworkspace, 8
      bind = $mainMod SHIFT, 9, movetoworkspace, 9
      bind = $mainMod SHIFT, 0, movetoworkspace, 10

      # Example special workspace (scratchpad)
      bind = $mainMod, S, togglespecialworkspace, magic
      bind = $mainMod SHIFT, S, movetoworkspace, special:magic

      # Scroll through existing workspaces with mainMod + scroll
      bind = $mainMod, mouse_down, workspace, e+1
      bind = $mainMod, mouse_up, workspace, e-1

      # Move/resize windows with mainMod + LMB/RMB and dragging
      bindm = $mainMod, mouse:272, movewindow
      bindm = $mainMod, mouse:273, resizewindow

      # Laptop multimedia keys for volume and LCD brightness
      bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
      bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
      bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
      bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
      bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
      bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

      ##############################
      ### WINDOWS AND WORKSPACES ###
      ##############################

      # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
      # See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

      # Example windowrule v1
      # windowrule = float, ^(kitty)$

      # Example windowrule v2
      # windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

      windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.


      ######## Stefan custom

      bind = $mainMod SHIFT, Q, exec, chromium

      bindl=,switch:on:Lid Switch,exec,loginctl lock-session
      bind = $mainMod CTRL, L, exec, loginctl lock-session
      bind = $mainMod CTRL, V, exec, code
      
      #bind = ALT, Tab, cyclenext,
      #bind = ALT, Tab, bringactivetotop,
      #bind = ALT SHIFT, Tab, cyclenext, prev

      # HYPRSWITCH
      $key = TAB
      $modifier = ALT
      $modifier_release = ALT_L
      $reverse = SHIFT

      # allows repeated switching with same keypress that starts the submap
      binde = $modifier, $key, exec, hyprswitch gui --do-initial-execute
      bind = $modifier, $key, submap, switch

      # allows repeated switching with same keypress that starts the submap
      binde = $modifier $reverse, $key, exec, hyprswitch gui --do-initial-execute -r
      bind = $modifier $reverse, $key, submap, switch

      submap = switch
      # allow repeated window switching in submap (same keys as repeating while starting)
      binde = $modifier, $key, exec, hyprswitch gui
      binde = $modifier $reverse, $key, exec, hyprswitch gui -r

      # switch to specific window offset (TODO replace with a more dynamic solution)
      bind = $modifier, 1, exec, hyprswitch gui --offset=1
      bind = $modifier, 2, exec, hyprswitch gui --offset=2
      bind = $modifier, 3, exec, hyprswitch gui --offset=3
      bind = $modifier, 4, exec, hyprswitch gui --offset=4
      bind = $modifier, 5, exec, hyprswitch gui --offset=5

      bind = $modifier $reverse, 1, exec, hyprswitch gui --offset=1 -r
      bind = $modifier $reverse, 2, exec, hyprswitch gui --offset=2 -r
      bind = $modifier $reverse, 3, exec, hyprswitch gui --offset=3 -r
      bind = $modifier $reverse, 4, exec, hyprswitch gui --offset=4 -r
      bind = $modifier $reverse, 5, exec, hyprswitch gui --offset=5 -r


      # exit submap and stop hyprswitch
      bindrt = $modifier, $modifier_release, exec, hyprswitch close
      bindrt = $modifier, $modifier_release, submap, reset

      # if it somehow doesn't close on releasing $switch_release, escape can kill (doesnt switch)
      bindr = ,escape, exec, hyprswitch close --kill
      bindr = ,escape, submap, reset
      submap = reset

      bind = SUPER,F,fullscreen

      # Screenshot testing

      bind = ,code:107,exec,grim -g "$(slurp)"
      bind = SHIFT,code:107,exec,grim -g "$(slurp -o)"
      bind = SUPER,code:107,exec,grim
      bind = CTRL,code:107,exec,grim -g "$(slurp)" - | wl-copy
      bind = SHIFTCTRL,code:107,exec,grim -g "$(slurp -o)" - | wl-copy
      bind = SUPERCTRL,code:107,exec,grim - | wl-copy
    '';
  };

  # HYPRLOCK Config
  home.file.".config/hypr/hyprlock.conf".text = ''
    background {
      monitor =
      path = screenshot

      # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
      blur_passes = 2
      blur_size = 3
      noise = 0.0117
      contrast = 0.8916
      brightness = 0.8172
      vibrancy = 0.1696
      vibrancy_darkness = 0.0
    }

    input-field {
      monitor =
      size = 200, 50
      outline_thickness = 3
      dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
      dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
      dots_center = false
      dots_rounding = -1 # -1 default circle, -2 follow input-field rounding
      fade_on_empty = true
      fade_timeout = 1000 # Milliseconds before fade_on_empty is triggered.
      placeholder_text = <i>Input Password...</i> # Text rendered in the input box when it's empty.
      hide_input = false
      rounding = -1 # -1 means complete rounding (circle/oval)
      fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
      fail_transition = 300 # transition time in ms between normal outer_color and fail_color
      capslock_color = -1
      numlock_color = -1
      bothlock_color = -1 # when both locks are active. -1 means don't change outer color (same for above)
      invert_numlock = false # change color if numlock is off
      swap_font_color = false # see below

      position = 0, -20
      halign = center
      valign = center
    }

    label {
      monitor =
      text = Yes Master?
      font_size = 25

      rotate = 0 # degrees, counter-clockwise

      position = 0, 160
      halign = center
      valign = center
    }

    label {
      monitor =
      text = $TIME
      font_size = 20
      font_family = Intel One Mono
      rotate = 0 # degrees, counter-clockwise

      position = 0, 80
      halign = center
      valign = center
    }
  '';
}
