# This is a placeholder hardware configuration for Raspberry Pi 4
# You should replace this with the actual hardware-configuration.nix 
# generated by nixos-generate-config when installing on the Pi

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usbhid" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Root filesystem - adjust device path as needed
  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS_SD";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  # Boot partition if using separate /boot
  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-label/FIRMWARE";
  #   fsType = "vfat";
  # };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}